### ISSUE TITLE
K8s integration with IAM Role

### ISSUE THREAD

**Issue by AmitBaranes** [tongueroo/aws-mfa-secure#7]
When running `aws eks update-kubeconfig` with `--role-arn` new entry created under `.kube/config`. which contains the following: 

```yaml
- name: arn:aws:eks:eu-west-1:123456789:cluster/xxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - yyy
      - --role
      - arn:aws:iam::123456789:role/admin
      command: aws
```

Any kubectl command or IDE for k8s failed to run due to the fact that `alias aws="aws-mfa-secure session"` contains a space, this caused the kubeconfig to fail the command.

My questions are -
1. Do you have any workaround?
2. Can you add another command to skip the `session` usage? ( e.g `aws-mfa-secure` without the `session` )

**Comment by ShaharHD** [comment]
Possible workaround can be:

```yaml
- name: arn:aws:eks:eu-west-1:123456789:cluster/xxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - session
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - yyy
      - --role
      - arn:aws:iam::123456789:role/admin
      command: aws-mfa-secure
```

as the alias is blocking somehow the passing of the additional needed arguments
